Covid_19_WebApp/Covid_19_WebApp/Controllers/ManagersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Covid_19_WebApp.Data;
using Covid_19_WebApp.Models;
using Microsoft.Data.SqlClient;
using System.Data;
using Newtonsoft.Json;

namespace Covid_19_WebApp.Controllers
{
    public class ManagersController : Controller
    {
        private readonly Covid_19_WebAppContext _context;

        public ManagersController(Covid_19_WebAppContext context)
        {
            _context = context;
        }

        // GET: Managers
        public async Task<IActionResult> Index()
        {
              return _context.Manager != null ? 
                          View(await _context.Manager.ToListAsync()) :
                          Problem("Entity set 'Covid_19_WebAppContext.Manager'  is null.");
        }

        // GET: Managers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Manager == null)
            {
                return NotFound();
            }

            var manager = await _context.Manager
                .FirstOrDefaultAsync(m => m.ManagerID == id);
            if (manager == null)
            {
                return NotFound();
            }

            return View(manager);
        }

        // GET: Managers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Managers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ManagerID,FName,LName,BDate,Address,Phone,Email,Password")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manager);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manager);
        }

        // GET: Managers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Manager == null)
            {
                return NotFound();
            }

            var manager = await _context.Manager.FindAsync(id);
            if (manager == null)
            {
                return NotFound();
            }
            return View(manager);
        }

        // POST: Managers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ManagerID,FName,LName,BDate,Address,Phone,Email,Password")] Manager manager)
        {
            if (id != manager.ManagerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manager);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ManagerExists(manager.ManagerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manager);
        }

        // GET: Managers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Manager == null)
            {
                return NotFound();
            }

            var manager = await _context.Manager
                .FirstOrDefaultAsync(m => m.ManagerID == id);
            if (manager == null)
            {
                return NotFound();
            }

            return View(manager);
        }

        // POST: Managers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Manager == null)
            {
                return Problem("Entity set 'Covid_19_WebAppContext.Manager'  is null.");
            }
            var manager = await _context.Manager.FindAsync(id);
            if (manager != null)
            {
                _context.Manager.Remove(manager);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManagerExists(int id)
        {
          return (_context.Manager?.Any(e => e.ManagerID == id)).GetValueOrDefault();
        }

        public IActionResult ManagerHomePage()
        {
            return View();
        }



        // Login
        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;

        // GET: Citizen
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        void connectionString()
        {
            connectionstring constring = new connectionstring();
            con.ConnectionString = constring.GetConnectionString();
        }


        [HttpPost]
        public ActionResult Verify(Manager manager)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "Select * from Manager where Email='" + manager.Email + "' and Password='" + manager.Password + "'";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                GlobalVariables.isManagerLogin = true;
                GlobalVariables.manager.FName = dr.GetString(1);
                con.Close();
                //return View("LoginSuccess");
            }
            else
            {
                GlobalVariables.isManagerAccountCorrect = false;
                con.Close();
            }
            return RedirectToAction("ManagerHome", "Home");
        }

        public IActionResult LogOut()
        {
            GlobalVariables.isManagerLogin = false;
            return RedirectToAction("ManagerHome", "Home");
        }

        public void Statistic_Number_Of_Citizen_Each_Month(int year)
        {
            List<int> Month = new List<int>();
            List<int> NumberOfCitizen = new List<int>();
            List<DataPoint> dataPoints = new List<DataPoint>();
            connectionstring constring = new connectionstring();
            DataTable data = new DataTable();
            //string query = "select @month as 'Month', COUNT(*) as 'Number of Citizen' from VACCINE_RECORD where MONTH(FirstDate) = @month or MONTH(SecondDate) = @month or MONTH(ThirdDate) = @month";
            string query = "select @month as 'Month', COUNT(*) as 'Number of Citizen' from VACCINE_RECORD where (MONTH(FirstDate) = @month or MONTH(SecondDate) = @month or MONTH(ThirdDate) = @month) and(YEAR(FirstDate) = @year or YEAR(SecondDate) = @year or YEAR(ThirdDate) = @year)";

            using (SqlConnection connection = new SqlConnection(constring.GetConnectionString()))
            {
                for (int i = 1; i <= 12; i++)
                {
                    SqlCommand command = new SqlCommand(query, connection);
                    command.Parameters.AddWithValue("@month", i);
                    command.Parameters.AddWithValue("@year", year);
                    connection.Open();
                    SqlDataReader reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                        //Month.Add(Convert.ToInt32(reader[0]));
                        //NumberOfCitizen.Add(Convert.ToInt32(reader[1]));
                        dataPoints.Add(new DataPoint(Convert.ToInt32(reader[0]), Convert.ToInt32(reader[1])));
                    }
                    connection.Close();
                }
            }
            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
        }

        public IActionResult GetChart_Statistic_Number_Of_Citizen_Each_Month(int year)
        {
            Statistic_Number_Of_Citizen_Each_Month(year);
            ViewBag.year = year;
            return View();
        }

        public void Statistic_Vaccine_For_InjectionNumber()
        {
            string[] VaccineOrder = { "FirstVaccine", "SecondVaccine", "ThirdVaccine" };
            List<DataPointForVaccine> dataPoints = new List<DataPointForVaccine>();
            connectionstring constring = new connectionstring();
            DataTable data = new DataTable();
            string query = "select Number_Injection, COUNT(CitizenID) from VACCINE_RECORD group by Number_Injection";
            using (SqlConnection connection = new SqlConnection(constring.GetConnectionString()))
            {
                SqlCommand command = new SqlCommand(query, connection);
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    //Month.Add(Convert.ToInt32(reader[0]));
                    //NumberOfCitizen.Add(Convert.ToInt32(reader[1]));
                    if (Convert.ToInt32(reader[0]) == 1)
                    {
                        dataPoints.Add(new DataPointForVaccine("First Vaccination", Convert.ToInt32(reader[1])));
                    }
                    else if (Convert.ToInt32(reader[0]) == 2)
                    {
                        dataPoints.Add(new DataPointForVaccine("Second Vaccination", Convert.ToInt32(reader[1])));

Covid_19_WebApp/Covid_19_WebApp/Controllers/VaccinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Covid_19_WebApp.Data;
using Covid_19_WebApp.Models;

namespace Covid_19_WebApp.Controllers
{
    public class VaccinesController : Controller
    {
        private readonly Covid_19_WebAppContext _context;

        public VaccinesController(Covid_19_WebAppContext context)
        {
            _context = context;
        }

        // GET: Vaccines
        public async Task<IActionResult> Index()
        {
              return _context.Vaccine != null ? 
                          View(await _context.Vaccine.ToListAsync()) :
                          Problem("Entity set 'Covid_19_WebAppContext.Vaccine'  is null.");
        }

        // GET: Vaccines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vaccine == null)
            {
                return NotFound();
            }

            var vaccine = await _context.Vaccine
                .FirstOrDefaultAsync(m => m.VaccineID == id);
            if (vaccine == null)
            {
                return NotFound();
            }

            return View(vaccine);
        }

        // GET: Vaccines/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vaccines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VaccineID,WarehouseID,VaccineName")] Vaccine vaccine)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vaccine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vaccine);
        }

        // GET: Vaccines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vaccine == null)
            {
                return NotFound();
            }

            var vaccine = await _context.Vaccine.FindAsync(id);
            if (vaccine == null)
            {
                return NotFound();
            }
            return View(vaccine);
        }

        // POST: Vaccines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VaccineID,WarehouseID,VaccineName")] Vaccine vaccine)
        {
            if (id != vaccine.VaccineID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vaccine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VaccineExists(vaccine.VaccineID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vaccine);
        }

        // GET: Vaccines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vaccine == null)
            {
                return NotFound();
            }

            var vaccine = await _context.Vaccine
                .FirstOrDefaultAsync(m => m.VaccineID == id);
            if (vaccine == null)
            {
                return NotFound();
            }

            return View(vaccine);
        }

        // POST: Vaccines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vaccine == null)
            {
                return Problem("Entity set 'Covid_19_WebAppContext.Vaccine'  is null.");
            }
            var vaccine = await _context.Vaccine.FindAsync(id);
            if (vaccine != null)
            {
                _context.Vaccine.Remove(vaccine);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VaccineExists(int id)
        {
          return (_context.Vaccine?.Any(e => e.VaccineID == id)).GetValueOrDefault();
        }
    }
}

Covid_19_WebApp/Covid_19_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Covid-19 Vaccine Portal</title>
    <link rel="icon" href="assets/images/icon-removebg-preview.png">
    <link rel="shortcut icon" href="assets/images/fav.jpg">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/fontawsom-all.min.css">
    <link rel="stylesheet" href="assets/css/animate.css">
    <link rel="stylesheet" type="text/css" href="assets/css/style.css" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css
">
</head>
<body>
     <!-- ################# Header Starts Here #######################--->
    <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 left-item">
                        <ul>
                            <li><i class="fas fa-envelope-square"></i> covid19vc@gmail.com</li>
                            <li><i class="fas fa-phone-square"></i> +84 987 887 765</li>
                        </ul>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block right-item">
                        <ul>
                            <li><a><i class="fab fa-github"></i></a></li>
                            <li><a><i class="fab fa-google-plus-g"></i></a></li>
                            <li> <a><i class="fab fa-pinterest-p"></i></a></li>
                            <li><a><i class="fab fa-twitter"></i></a></li>
                            <li> <a><i class="fab fa-facebook-f"></i></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <div id="nav-head" class="header-nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-12 nav-img">
                        <img src="~/logo.jpg" alt="">
                       <a data-toggle="collapse" data-target="#menu" href="#menu" ><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                    </div>
                    <div id="menu" class="col-md-9 d-none d-md-block nav-item">
                        <ul>
                            <li><a href="@Url.Action("index", "Home")">Home</a></li>
                            
                            @*<li><a href="Search.html">Search</a></li>*@
                            <li><a href="@Url.Action("ContactUs","Home")">Contact Us</a></li>

                            @{
                                if (GlobalVariables.isLogin == false)
                                {
                                    //<li><a href="@Url.Action("Create", "Citizens")">Sign Up</a></li>
                                    <li> <form method="get" action="@Url.Action("Login", "Citizens")">
                                            <button type="submit">Login</button>
                                        </form> 
                                    </li>
                                }
                                else if (GlobalVariables.isLogin == true)
                                {
                                    //<li>Hello @GlobalVariables.FName @GlobalVariables.LName </li>
                                    //<li> <form method="get" action="@Url.Action("LogOut", "Citizens")">
                                    //        <button type="submit">Logout</button>
                                    //    </form> 
                                    //</li>
                                    <li><a href="@Url.Action("Create", "VACCINE_REGISTRATION_FORM")">Vaccine Registration</a></li>
                                    <li><a href="@Url.Action("VaccinationHistory", "Citizens")">Search</a></li>

                                    <li class="dropdown">
                                        <button class="dropbtn">Hello @GlobalVariables.citizen.FName
                                            <i class="fa fa-caret-down"></i>
                                        </button>
                                        <div class="dropdown-content">
                                            <a href="@Url.Action("UserInformation", "Citizens")">About Me</a>
                                            <a href="@Url.Action("GetRegistrationForm", "Citizens")">My Registration Form</a>
                                            <a href="@Url.Action("LogOut", "Citizens")">Log out</a>
                                        </div>
                                    </li>
                                    
                                    
                                }

                            }
                            
                            @*<div class="usericon">
                                <a href="user.html"><img src="~/usericon.png" alt=""> </a>
                                <li> <a href="user.html">UserProfile</a></li>
                            </div> *@
                        </ul>
                    </div>
                </div>

            </div>
        </div>

    </header>
    <!-- ################# Header Ends Here #######################--->
    

    @RenderBody()
    @RenderSection("Styles", false)
    

     <!-- ################# Footer Starts Here #######################--->


     <div class="copy">
            <div class="container">
                <a href="https://www.smarteyeapps.com/">2015 &copy; All Rights Reserved | Designed and Developed by Smarteyeapps</a>
                
                <span>
                <a><i class="fab fa-github"></i></a>
                <a><i class="fab fa-google-plus-g"></i></a>
                <a><i class="fab fa-pinterest-p"></i></a>
                <a><i class="fab fa-twitter"></i></a>
                <a><i class="fab fa-facebook-f"></i></a>
        </span>
            </div>

        </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <h2>About Us</h2>
                    <p>Vaccines save millions of lives every year. Developing a safe and effective COVID-19 vaccine is a big step forward in our global effort to end the pandemic and get us back to doing better with the people we love.</p>
                    <p>We always try and help the Vietnamese people to fight the ovid-19 pandemic. The goal of the project is that we always focus on giving our best support to our compatriots and try to keep people living in Vietnam safe and including foreigners.  </p>
                </div>
                <div class="col-md-4 col-sm-12">
                    <h2>Useful Links</h2>
                    <ul class="list-unstyled link-list">
                        <li><a ui-sref="about" href="#/about">About us</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="portfolio" href="#/portfolio">Portfolio</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="products" href="#/products">Latest jobs</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="gallery" href="#/gallery">Gallery</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="contact" href="#/contact">Contact us</a><i class="fa fa-angle-right"></i></li>
                    </ul>
                </div>
                <div class="col-md-4 col-sm-12 map-img">
                    <h2>Contact Us</h2>
                    <address class="md-margin-bottom-40">
                        UIT-Team4 <br>
                        MSIS3303.M22.CTTT <br>
                        IT University <br>
                        Phone: +84 987 887 765 <br>
                        Email: <a>covid19vc@gmail.com</a><br>
                    </address>

                </div>
            </div>
        </div>
        

    </footer>

    <!-- ################# Footer Ends Here #######################--->
<script src="assets/js/jquery-3.2.1.min.js"></script>
<script src="assets/js/popper.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/plugins/scroll-fixed/jquery-scrolltofixed-min.js"></script>
<script src="assets/js/script.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Covid_19_WebApp/Covid_19_WebApp/Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Covid-19 Vaccine Portal</title>
    <link rel="icon" href="assets/images/icon-removebg-preview.png">
    <link rel="shortcut icon" href="assets/images/fav.jpg">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/fontawsom-all.min.css">
    <link rel="stylesheet" href="assets/css/animate.css">
    <link rel="stylesheet" type="text/css" href="assets/css/style.css" />
</head>
<body>
     <!-- ################# Header Starts Here #######################--->
    <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 left-item">
                        <ul>
                            <li><i class="fas fa-envelope-square"></i> covid19vc@gmail.com</li>
                            <li><i class="fas fa-phone-square"></i> +84 987 887 765</li>
                        </ul>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block right-item">
                        <ul>
                            <li><a><i class="fab fa-github"></i></a></li>
                            <li><a><i class="fab fa-google-plus-g"></i></a></li>
                            <li> <a><i class="fab fa-pinterest-p"></i></a></li>
                            <li><a><i class="fab fa-twitter"></i></a></li>
                            <li> <a><i class="fab fa-facebook-f"></i></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        @if (GlobalVariables.isManagerLogin == true)
        {
             <div id="nav-head" class="header-nav">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-12 nav-img">
                            <img src="~/logo.jpg" alt="">
                           <a data-toggle="collapse" data-target="#menu" href="#menu" ><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                        </div>
                        <div id="menu" class="col-md-9 d-none d-md-block nav-item">
                            <ul>
                                <li><a href="@Url.Action("ManagerHome", "Home")">Home</a></li>
                                <li><a href="@Url.Action("Index", "Vaccines")">Vaccine</a></li>
                                <li><a href="@Url.Action("Index", "VACCINE_REGISTRATION_FORM")">Vaccination Registration</a></li>
                                <li><a href="@Url.Action("Index", "Citizens")">Citizens</a></li>
                                <li><a href="@Url.Action("Index", "Nurses")">Nurse</a></li>
                                 <li class="dropdown">
                                        <button class="dropbtn">Hello @GlobalVariables.manager.FName
                                            <i class="fa fa-caret-down"></i>
                                        </button>
                                        <div class="dropdown-content">
                                            <a href="@Url.Action("Index", "Vaccine_Record")">Vaccination Records</a>
                                            <a href="@Url.Action("Index", "Warehouse_Vaccine")">Stock of Vaccines</a>
                                            <a href="@Url.Action("GetChart_Statistic_Number_Of_Citizen_Each_Month", "Managers")">Monthly Statistic</a>
                                            <a href="@Url.Action("GetChart_Statistic_Vaccine_For_InjectionNumber", "Managers")">Vaccination Statistic</a>
                                            <a href="@Url.Action("LogOut", "Managers")">Log out</a>
                                            
                                        </div>
                                 </li>
                            
                            
                                @*<div class="usericon">
                                    <a href="user.html"><img src="~/usericon.png" alt=""> </a>
                                    <li> <a href="user.html">UserProfile</a></li>
                                </div> *@
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        }
       

    </header>
    <!-- ################# Header Ends Here #######################--->
    

    @RenderBody()
    @RenderSection("Styles", false)
    

     <!-- ################# Footer Starts Here #######################--->


     <div class="copy">
            <div class="container">
                <a href="https://www.smarteyeapps.com/">2015 &copy; All Rights Reserved | Designed and Developed by Smarteyeapps</a>
                
                <span>
                <a><i class="fab fa-github"></i></a>
                <a><i class="fab fa-google-plus-g"></i></a>
                <a><i class="fab fa-pinterest-p"></i></a>
                <a><i class="fab fa-twitter"></i></a>
                <a><i class="fab fa-facebook-f"></i></a>
        </span>
            </div>

        </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <h2>About Us</h2>
                    <p>Vaccines save millions of lives every year. Developing a safe and effective COVID-19 vaccine is a big step forward in our global effort to end the pandemic and get us back to doing better with the people we love.</p>
                    <p>We always try and help the Vietnamese people to fight the ovid-19 pandemic. The goal of the project is that we always focus on giving our best support to our compatriots and try to keep people living in Vietnam safe and including foreigners.  </p>
                </div>
                <div class="col-md-4 col-sm-12">
                    <h2>Useful Links</h2>
                    <ul class="list-unstyled link-list">
                        <li><a ui-sref="about" href="#/about">About us</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="portfolio" href="#/portfolio">Portfolio</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="products" href="#/products">Latest jobs</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="gallery" href="#/gallery">Gallery</a><i class="fa fa-angle-right"></i></li>
                        <li><a ui-sref="contact" href="#/contact">Contact us</a><i class="fa fa-angle-right"></i></li>
                    </ul>
                </div>
                <div class="col-md-4 col-sm-12 map-img">
                    <h2>Contact Us</h2>
                    <address class="md-margin-bottom-40">
                        UIT-Team4 <br>
                        MSIS3303.M22.CTTT <br>
                        IT University <br>
                        Phone: +84 987 887 765 <br>
                        Email: <a>covid19vc@gmail.com</a><br>
                    </address>

                </div>
            </div>
        </div>
        

    </footer>

    <!-- ################# Footer Ends Here #######################--->
<script src="assets/js/jquery-3.2.1.min.js"></script>
<script src="assets/js/popper.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/plugins/scroll-fixed/jquery-scrolltofixed-min.js"></script>
<script src="assets/js/script.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>